### ISSUE TITLE
Derniers ajustements

### ISSUE THREAD

**Issue by arnaudlevy** [noesya/coop.noesya.www#1]
- [x] anim moche dans le menu qui s’ouvre (typo pas stable)
- [x] marges fausses dans les resume en mobile
- [x] les sup et notes à prendre dans la typo et pas en réduit comme maintenant
- [x] peut-être mettre les réalisations en nb / couleur hover @Alexis BENOIT non ?
- [x] minifier le js
- [x] animer les previous next comme tu voulais @alexisben 
- [x] caler le lighthouse 100% sur les autres pages (https://lighthouse-dot-webdotdevsite.appspot.com//lh/html?url=https%3A%2F%2Fnoesya-www.netlify.app%2Fequipe%2Farnaud-levy)
- [x] masquer le menu mobile au scroll, afficher en remontant 
- [x] j'ai fait un filet comme j'ai pu dans le prev next mobile, ce serait mieux pleine largeur mais je sais pas le faire
- [x] actuellement l'anim à gauche ne va pas jusqu'au bord
<img width="1792" alt="Capture d’écran 2021-10-03 à 10 06 30" src="https://user-images.githubusercontent.com/2088968/135745442-644c5def-5e74-451a-9ecd-b268bb8306b9.png">

- [x] l'anim du précédent devrait aller du centre vers la gauche, sauf sur la home 
- [x] faire le darkmode
- [x] le gris est pas assez contrasté https://lighthouse-dot-webdotdevsite.appspot.com//lh/html?url=https%3A%2F%2Fnoesya-www.netlify.app%2Fequipe%2F#accessibility
- [x] gris pas assez contrasté https://lighthouse-dot-webdotdevsite.appspot.com//lh/html?url=https%3A%2F%2Fnoesya-www.netlify.app%2Fcommuns-numeriques#accessibility
- [x] micro-détail, en mobile, on ne peut pas voir la première note si 2 sont sur la même ligne (communs)
- [x] si on peut éviter que l’icône “lien externe” se retrouve toute seule, c’est top
- [x] les pages mentions légales et politique de confidentialité manque d'une fin de page (marge en bas)

**Comment by arnaudlevy** [comment]
https://css-tricks.com/almanac/properties/f/font-feature-settings/
Sarah a relu et donné ça pour les sup

**Comment by arnaudlevy** [comment]
<img width="339" alt="Capture d’écran 2021-10-01 à 07 11 22" src="https://user-images.githubusercontent.com/2088968/135568585-3a21ffb2-372e-445b-ac25-981af028b73a.png">

**Comment by arnaudlevy** [comment]
Pour les 2 notes sur la même ligne je peux supprimer le cas

**Comment by arnaudlevy** [comment]
Sur iPhone 8 le menu est calé, sur un tel moins haut ça passe ?

**Comment by alexisben** [comment]
> Sur iPhone 8 le menu est calé, sur un tel moins haut ça passe ?

Ça passe sur mon SE (format iphone 6)

Mais à ce sujet je réduirais un peu le line height en mobile, je trouve qu'on distingue pas très bien les titres sur 2 lignes

**Comment by arnaudlevy** [comment]
précédent suivant cassé (alignement gauche) @alexisben 
<img width="1625" alt="Capture d’écran 2021-10-03 à 10 22 01" src="https://user-images.githubusercontent.com/2088968/135745814-2af0f30b-d85e-4690-9708-09fb6782099b.png">
