### ISSUE TITLE
DA - vérifier interlignage footer en desktop + logo b corp

### ISSUE THREAD

**Issue by Violenn** [noesya/coop.noesya.www#2]
Hello

- [ ] En desktop l'interlignage entre les items du footer devrait avoir 30px de plus, voir : 

![Capture d’écran 2021-10-04 à 14 58 20](https://user-images.githubusercontent.com/84067177/135856065-3a6fa748-a65d-4c36-a275-3dff4671585f.png)

(on arrive au bas de la chouette avec labs)

- [x] Manque le logo B corp

**Comment by arnaudlevy** [comment]
Le logo b corp on a pas encore eu le statut, c'est long
